"""
Email HTML & Plaintext Templates for Gmail Integration.
Provides responsive, branded email designs for OTPs and security alerts.
"""

from .config import APP_NAME, APP_URL, OTP_EXPIRY_MINUTES

def get_base_email_html(title: str, preheader: str, content_html: str, footer_note: str = "") -> str:
    """Base responsive HTML email layout with modern gradient styling."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>
    body {{
      margin: 0;
      padding: 0;
      background-color: #f1f5f9;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      color: #1e293b;
      -webkit-font-smoothing: antialiased;
    }}
    .email-wrapper {{
      width: 100%;
      background-color: #f1f5f9;
      padding: 40px 15px;
    }}
    .email-container {{
      max-width: 540px;
      margin: 0 auto;
      background-color: #ffffff;
      border-radius: 16px;
      overflow: hidden;
      box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.08), 0 8px 10px -6px rgba(0, 0, 0, 0.04);
      border: 1px solid #e2e8f0;
    }}
    .email-header {{
      background: linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%);
      padding: 32px 24px;
      text-align: center;
      color: #ffffff;
    }}
    .email-header h1 {{
      margin: 0;
      font-size: 24px;
      font-weight: 700;
      letter-spacing: -0.5px;
    }}
    .email-header p {{
      margin: 6px 0 0 0;
      font-size: 14px;
      color: #bfdbfe;
    }}
    .email-body {{
      padding: 36px 28px;
    }}
    .email-body h2 {{
      margin: 0 0 16px 0;
      font-size: 20px;
      color: #0f172a;
      font-weight: 600;
    }}
    .email-body p {{
      margin: 0 0 16px 0;
      font-size: 15px;
      line-height: 1.6;
      color: #475569;
    }}
    .otp-card {{
      background: linear-gradient(135deg, #eff6ff 0%, #f0fdf4 100%);
      border: 2px dashed #93c5fd;
      border-radius: 12px;
      padding: 24px;
      text-align: center;
      margin: 24px 0;
    }}
    .otp-code {{
      font-family: 'Courier New', Courier, monospace;
      font-size: 36px;
      font-weight: 800;
      letter-spacing: 8px;
      color: #1d4ed8;
      margin: 8px 0;
      user-select: all;
    }}
    .otp-expiry {{
      font-size: 13px;
      color: #64748b;
      margin-top: 6px;
    }}
    .security-badge {{
      display: inline-block;
      background-color: #fef2f2;
      border: 1px solid #fecaca;
      color: #991b1b;
      padding: 8px 14px;
      border-radius: 8px;
      font-size: 13px;
      margin-top: 12px;
    }}
    .email-footer {{
      background-color: #f8fafc;
      padding: 20px 24px;
      text-align: center;
      border-top: 1px solid #e2e8f0;
      font-size: 12px;
      color: #94a3b8;
      line-height: 1.5;
    }}
    .email-footer a {{
      color: #2563eb;
      text-decoration: none;
    }}
    .preheader {{
      display: none;
      font-size: 1px;
      color: #f1f5f9;
      line-height: 1px;
      max-height: 0px;
      max-width: 0px;
      opacity: 0;
      overflow: hidden;
    }}
  </style>
</head>
<body>
  <div class="preheader">{preheader}</div>
  <div class="email-wrapper">
    <div class="email-container">
      <div class="email-header">
        <h1>🔐 {APP_NAME}</h1>
        <p>Zero-Knowledge & Self-Hosted Vault</p>
      </div>
      <div class="email-body">
        {content_html}
      </div>
      <div class="email-footer">
        <p>{footer_note if footer_note else f"This security message was automatically generated by {APP_NAME}."}</p>
        <p>If you did not request this code, please ignore this email or check your account security.</p>
        <p><a href="{APP_URL}">{APP_URL}</a></p>
      </div>
    </div>
  </div>
</body>
</html>
"""


def render_registration_otp_email(username: str, otp_code: str, expiry_minutes: int = OTP_EXPIRY_MINUTES) -> tuple[str, str]:
    """
    Renders (html_body, text_body) for New Account Registration OTP Verification.
    """
    subject = f"Verify your new account - {APP_NAME}"
    preheader = f"Your verification code is {otp_code}. Valid for {expiry_minutes} minutes."
    
    content_html = f"""
      <h2>Welcome to {APP_NAME}, {username}! 👋</h2>
      <p>Thank you for signing up. To complete your account registration and verify your email address, please enter the one-time verification code below:</p>
      
      <div class="otp-card">
        <div style="font-size: 13px; text-transform: uppercase; letter-spacing: 1px; color: #475569; font-weight: 600;">Account Verification Code</div>
        <div class="otp-code">{otp_code}</div>
        <div class="otp-expiry">⏱ Valid for the next <strong>{expiry_minutes} minutes</strong></div>
      </div>

      <p>Once verified, your account will be activated with zero-knowledge encryption ready for your passwords and vaults.</p>
      
      <div class="security-badge">
        ⚠️ <strong>Security Notice:</strong> Never share this code with anyone. Our team will never ask for your verification code.
      </div>
    """
    
    html = get_base_email_html(
        title=subject,
        preheader=preheader,
        content_html=content_html
    )
    
    text = (
        f"Welcome to {APP_NAME}, {username}!\n\n"
        f"Your verification code to complete your registration is:\n\n"
        f"   {otp_code}\n\n"
        f"This code will expire in {expiry_minutes} minutes.\n\n"
        f"If you did not create an account on {APP_NAME}, please ignore this email.\n"
    )
    
    return html, text


def render_password_reset_otp_email(username: str, otp_code: str, expiry_minutes: int = OTP_EXPIRY_MINUTES) -> tuple[str, str]:
    """
    Renders (html_body, text_body) for Forgot Password / One-Time Login / Password Reset.
    """
    subject = f"Password Reset & One-Time Login Code - {APP_NAME}"
    preheader = f"Your one-time code is {otp_code}. Use this to log in or reset your password."
    
    content_html = f"""
      <h2>Password Recovery Request 🔑</h2>
      <p>Hello <strong>{username}</strong>,</p>
      <p>We received a request to recover your password or log in to your account. Use the one-time code below to proceed:</p>
      
      <div class="otp-card">
        <div style="font-size: 13px; text-transform: uppercase; letter-spacing: 1px; color: #475569; font-weight: 600;">One-Time Security Code</div>
        <div class="otp-code">{otp_code}</div>
        <div class="otp-expiry">⏱ Valid for the next <strong>{expiry_minutes} minutes</strong></div>
      </div>

      <p>With this code, you can:</p>
      <ul style="color: #475569; line-height: 1.8; font-size: 14px; margin-bottom: 20px;">
        <li><strong>Log in immediately</strong> via one-time authenticated session.</li>
        <li><strong>Update your master password</strong> securely.</li>
      </ul>
      
      <div class="security-badge">
        ⚠️ <strong>Important:</strong> If you did not make this request, someone else may be attempting to access your account. Ensure your email account is secure.
      </div>
    """
    
    html = get_base_email_html(
        title=subject,
        preheader=preheader,
        content_html=content_html
    )
    
    text = (
        f"Hello {username},\n\n"
        f"A password reset / one-time login request was received for your {APP_NAME} account.\n\n"
        f"Your one-time security code is:\n\n"
        f"   {otp_code}\n\n"
        f"This code is valid for {expiry_minutes} minutes.\n\n"
        f"You can use this code to log in directly or set a new master password.\n\n"
        f"If you did not request this, please ignore this email.\n"
    )
    
    return html, text


def render_password_changed_email(username: str) -> tuple[str, str]:
    """
    Renders (html_body, text_body) alert when master password is changed.
    """
    subject = f"Security Alert: Master Password Changed - {APP_NAME}"
    preheader = f"Your master password was recently updated on {APP_NAME}."
    
    content_html = f"""
      <h2>Security Alert 🛡️</h2>
      <p>Hello <strong>{username}</strong>,</p>
      <p>This is a confirmation that the master password for your <strong>{APP_NAME}</strong> account was recently changed.</p>
      <div class="security-badge" style="display: block; margin: 20px 0;">
        ⚠️ If you performed this change, you can safely disregard this email.<br/>
        If you did NOT perform this change, please contact your system administrator immediately.
      </div>
    """
    
    html = get_base_email_html(
        title=subject,
        preheader=preheader,
        content_html=content_html
    )
    
    text = (
        f"Hello {username},\n\n"
        f"Your master password on {APP_NAME} was recently updated.\n\n"
        f"If you did not make this change, please contact your administrator immediately.\n"
    )
    
    return html, text
